---
version: "3.9"
services:
  devopsdb:
    image: msdinesh98/automation:db
    ports:
      - "3306:3306"
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - mynetwork
  application:
    image: msdinesh98/automation:app
    ports:
      - "1212:8080"
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      - mynetwork
    depends_on:
      - "devopsdb"
networks:
  mynetwork:
    driver: overlay
...
